import type { IntentKnowledge } from "@/lib/chat/types";

export const INTENT_KNOWLEDGE: IntentKnowledge[] = [
  {
    id: "custom_trip",
    keywords: [
      "custom",
      "tailor",
      "personalized",
      "itinerary",
      "plan",
      "planning",
      "budget trip",
      "trip style",
      "مخصص",
      "تخصيص",
      "برنامج",
      "ميزانية",
      "خطة",
      "planifier",
      "sur mesure",
      "personnaliser",
      "itineraire",
      "budget",
    ],
    answerKey: "faq.sections.planning.items.q2.answer",
    followUpKey: "chat.followUps.planStart",
    suggestions: ["budget_booking", "morocco", "contact_whatsapp"],
  },
  {
    id: "morocco",
    keywords: [
      "morocco",
      "marrakech",
      "fes",
      "chefchaouen",
      "sahara",
      "tangier",
      "rabat",
      "casablanca",
      "المغرب",
      "مراكش",
      "فاس",
      "شفشاون",
      "الصحراء",
      "طنجة",
      "الرباط",
      "الدار البيضاء",
      "maroc",
      "marrakech",
      "fes",
      "chefchaouen",
      "sahara",
      "tanger",
      "rabat",
      "casablanca",
    ],
    answerKey: "faq.sections.morocco.items.q1.answer",
    followUpKey: "chat.followUps.moroccoCombine",
    suggestions: ["agadir", "budget_booking", "contact_whatsapp"],
  },
  {
    id: "tunisia",
    keywords: [
      "tunisia",
      "tunis",
      "سياحة تونس",
      "تونس",
      "sousse",
      "kairouan",
      "tunisie",
      "tunisie voyage",
    ],
    answerKey: "faq.sections.destinations.items.q2.answer",
    followUpKey: "chat.followUps.tunisiaBlend",
    suggestions: ["custom_trip", "budget_booking", "contact_whatsapp"],
  },
  {
    id: "saudi",
    keywords: [
      "saudi",
      "ksa",
      "saudi arabia",
      "السعودية",
      "المملكة",
      "riyadh",
      "jeddah",
      "arabie saoudite",
      "arabie",
    ],
    answerKey: "faq.sections.destinations.items.q3.answer",
    followUpKey: "chat.followUps.saudiStyle",
    suggestions: ["riyadh_jeddah", "custom_trip", "contact_whatsapp"],
  },
  {
    id: "riyadh_jeddah",
    keywords: [
      "riyadh",
      "jeddah",
      "riyadh trip",
      "jeddah trip",
      "الرياض",
      "جدة",
      "رحلة الرياض",
      "رحلة جدة",
      "riyad",
      "djeddah",
    ],
    answerKey: "faq.sections.destinations.items.q3.answer",
    followUpKey: "chat.followUps.riyadhJeddah",
    suggestions: ["saudi", "budget_booking", "contact_whatsapp"],
  },
  {
    id: "agadir",
    keywords: [
      "agadir",
      "essaouira",
      "jeep safari",
      "quad",
      "surf",
      "hammam",
      "atlas",
      "agadir day trip",
      "اغادير",
      "أغادير",
      "الصويرة",
      "جيب",
      "كواد",
      "سيرف",
      "حمام",
      "اطلس",
      "atlas",
      "essaouira",
    ],
    answerKey: "faq.sections.morocco.items.q3.answer",
    followUpKey: "chat.followUps.agadirDesign",
    suggestions: ["morocco", "budget_booking", "contact_whatsapp"],
  },
  {
    id: "hotels_services",
    keywords: [
      "hotel",
      "4 star",
      "5 star",
      "luxury",
      "transfer",
      "airport",
      "driver",
      "guide",
      "tour",
      "فنادق",
      "فندق",
      "٤ نجوم",
      "5 نجوم",
      "نقل",
      "مطار",
      "سائق",
      "مرشد",
      "جولات",
      "hotel",
      "transfert",
      "aeroport",
      "guide",
      "visite",
      "luxe",
    ],
    answerKey: "faq.sections.services.items.q1.answer",
    followUpKey: "chat.followUps.servicesMatch",
    suggestions: ["budget_booking", "family_honeymoon", "contact_whatsapp"],
  },
  {
    id: "budget_booking",
    keywords: [
      "price",
      "pricing",
      "cost",
      "budget",
      "book",
      "booking",
      "deposit",
      "quote",
      "سعر",
      "تكلفة",
      "ميزانية",
      "حجز",
      "عربون",
      "prix",
      "tarif",
      "budget",
      "reservation",
      "acompte",
    ],
    answerKey: "faq.sections.budget.items.q1.answer",
    followUpKey: "chat.followUps.budgetShare",
    suggestions: ["custom_trip", "contact_whatsapp"],
  },
  {
    id: "family_honeymoon",
    keywords: [
      "family",
      "kids",
      "honeymoon",
      "couple",
      "romantic",
      "women only",
      "travel style",
      "عائلة",
      "عائلي",
      "اطفال",
      "شهر عسل",
      "زوجين",
      "خصوصية",
      "famille",
      "enfants",
      "lune de miel",
      "couple",
      "prive",
    ],
    answerKey: "faq.sections.travelStyle.items.q1.answer",
    followUpKey: "chat.followUps.styleTailored",
    suggestions: ["custom_trip", "hotels_services", "contact_whatsapp"],
  },
  {
    id: "contact_whatsapp",
    keywords: [
      "whatsapp",
      "contact",
      "agent",
      "team",
      "support",
      "واتساب",
      "تواصل",
      "الفريق",
      "دعم",
      "whats app",
      "equipe",
      "support",
      "contacter",
    ],
    answerKey: "faq.sections.support.items.q1.answer",
    followUpKey: "chat.followUps.whatsappNow",
    suggestions: ["custom_trip", "budget_booking"],
  },
];
