import type { Program, ProgramValueProp } from "@/lib/programs/types";

export const PROGRAMS_PRIMARY_COLOR = "#2C1622";
export const PROGRAMS_BG_COLOR = "#E1E0D4";
export const PROGRAMS_FALLBACK_IMAGE = "/assets/hero.webp";

export const DEFAULT_CATEGORIES = [
  "Nature",
  "Adventure",
  "Culture",
  "Wellness",
  "Coastal",
  "Multi-Day",
] as const;

export const SELECTED_RAIL_SLUGS = new Set<string>([]);

export const VALUE_PROPS: ProgramValueProp[] = [
  {
    title: "Curated Experiences",
    description:
      "Each itinerary is carefully designed for comfort, authenticity, and meaningful discovery.",
  },
  {
    title: "Trusted Local Guides",
    description:
      "Travel with knowledgeable hosts who understand every region, route, and hidden story.",
  },
  {
    title: "Flexible Planning",
    description:
      "Adjust the pace, stops, and style of your program to fit your travel goals.",
  },
  {
    title: "Premium Destinations",
    description:
      "From coastal escapes to mountain journeys, enjoy elevated routes and refined moments.",
  },
];

export const MOROCCO_PROGRAMS: Program[] = [
  {
    id: "program-paradise-valley-atlas",
    slug: "paradise-valley-atlas-mountains",
    title: "Paradise Valley & Atlas Mountains",
    category: "Nature",
    region: "Agadir / Taghazout",
    destination: "Agadir / Taghazout",
    duration: "Full day",
    shortDescription:
      "Discover natural pools, green valleys, and fresh mountain air between Paradise Valley, Immouzer, and the Atlas Mountains.",
    places: ["Paradise Valley", "Atlas Mountains", "Immouzer"],
    highlights: [
      "Natural pools and waterfalls",
      "Hiking in a green valley",
      "Mountain landscapes and fresh air",
    ],
    coverImage: "/assets/Paradise_Valley_&_Atlas_Mountains.jpg",
    gallery: [
      "/assets/paradise2.png",
      "/assets/Paradise_Valley_&_Atlas_Mountains.jpg",
      "/assets/Parc_Perdicaris_in_Tangier   (1).png",
      "/assets/paradise3.png",
    ],
    order: 1,
    isActive: true,
  },
  {
    id: "program-jeep-safari-desert",
    slug: "jeep-safari-desert-adventure",
    title: "Jeep Safari Desert Adventure",
    category: "Adventure",
    region: "Agadir",
    destination: "Agadir",
    duration: "Full day",
    shortDescription:
      "A full adventure through wild beaches, desert roads, Berber flavors, and the small Sahara dunes.",
    places: [
      "Souss Massa National Park",
      "Tiznit",
      "Youssef Ibn Tachfine Dam",
      "Sahara Desert",
    ],
    highlights: [
      "4x4 off-road adventure",
      "Fishermen caves and wild beaches",
      "Flamingos and wildlife",
      "Berber lunch with tagine and couscous",
      "Small Sahara dunes",
    ],
    coverImage: "/assets/desert.webp",
    gallery: [
      "/assets/jeep_safari2.jpg",
      "/assets/jeep_safari3.jpg",
      "/assets/jeep_safari4.jpg",
    ],
    order: 2,
    isActive: true,
  },
  {
    id: "program-tafraoute-anti-atlas",
    slug: "tafraoute-anti-atlas-mountains",
    title: "Tafraoute & Anti-Atlas Mountains",
    category: "Nature",
    region: "Anti-Atlas",
    destination: "Anti-Atlas",
    duration: "Full day",
    shortDescription:
      "Explore the peaceful Anti-Atlas, famous for dramatic rocks, hidden oases, and authentic Berber atmosphere.",
    places: ["Tafraoute", "Anti-Atlas Mountains"],
    highlights: [
      "Unique rock formations",
      "Hidden oasis landscapes",
      "Calm and authentic Berber environment",
    ],
    coverImage: "/assets/Tafraoute1.jpg",
    gallery: [
      "/assets/Tafraoute1.jpg",
      "/assets/Tafraoute2.jpg",
      "/assets/Tafraoute3.jpg",
      "/assets/Tafraoute4.jpg",
    ],
    order: 3,
    isActive: true,
  },
  {
    id: "program-berber-village-cooking",
    slug: "berber-village-cooking-experience",
    title: "Berber Village Cooking Experience",
    category: "Culture",
    region: "Atlas Mountains",
    destination: "Atlas Mountains",
    duration: "Half day",
    shortDescription:
      "A cultural food experience inside traditional Berber villages with local cooking, tea rituals, and warm hospitality.",
    places: ["Atlas Mountains", "Traditional Berber villages"],
    badge: "Local Favorite",
    highlights: [
      "Cooking tagine and couscous",
      "Tea ceremony",
      "Discover Berber lifestyle",
    ],
    coverImage: "/assets/hammam1.jpg",
    gallery: [
      "/assets/Berber_Village_Cooking_Experience.jpg",
      "/assets/jeep_safari4.jpg",
    ],
    order: 4,
    isActive: true,
  },
  {
    id: "program-agadir-city-tour",
    slug: "agadir-city-tour",
    title: "Agadir City Tour",
    category: "Culture",
    region: "Agadir",
    destination: "Agadir",
    duration: "Half day",
    shortDescription:
      "See Agadir from above, visit Crocopark, and discover the city's culture, views, and local highlights.",
    places: ["Kasbah Oufella", "Crocopark", "Agadir"],
    highlights: [
      "Cable car panoramic views",
      "Crocodiles and botanical garden",
      "Goats climbing argan trees",
    ],
    coverImage: "/assets/aghadir1.jpg",
    order: 5,
    isActive: true,
  },
  {
    id: "program-hammam-spa",
    slug: "hammam-spa-experience",
    title: "Hammam & Spa Experience",
    category: "Wellness",
    region: "Agadir",
    destination: "Agadir",
    duration: "Half day",
    shortDescription:
      "A relaxing Moroccan wellness ritual with hammam, black soap exfoliation, and calming massage oils.",
    places: ["Agadir Spa Centers"],
    highlights: [
      "Traditional hammam",
      "Black soap exfoliation",
      "Relaxing massage with oils",
    ],
    coverImage: "/assets/hammam1.jpg",
    order: 6,
    isActive: true,
  },
  {
    id: "program-taroudant-tiout",
    slug: "taroudant-tiout-day-trip",
    title: "Taroudant & Tiout Day Trip",
    category: "Culture",
    region: "Taroudant / Tiout",
    destination: "Taroudant / Tiout",
    duration: "Full day",
    shortDescription:
      "A heritage day trip through ancient walls, traditional souks, oasis landscapes, and Moroccan countryside.",
    places: ["Taroudant", "Tiout"],
    highlights: [
      "Ancient city walls and souks",
      "Oasis and kasbah",
      "Authentic Moroccan countryside",
    ],
    coverImage: "/assets/aghadeer.jpg",
    gallery: [
      "/assets/tardaoui1.png",
      "/assets/tardaoui2.png",
      "/assets/tardaoui3.png",
      "/assets/tardaoui4.png",
      "/assets/tardaoui6.png",
    ],
    order: 7,
    isActive: true,
  },
  {
    id: "program-surf-experience",
    slug: "surf-experience-agadir",
    title: "Surf Experience",
    category: "Adventure",
    region: "Agadir Beach",
    destination: "Agadir Beach",
    duration: "Half day",
    shortDescription:
      "Enjoy Atlantic waves and Moroccan beach culture with surf lessons suitable for all levels.",
    places: ["Agadir Beach"],
    highlights: [
      "Surf lessons for all levels",
      "Atlantic waves",
      "Moroccan surf culture",
    ],
    coverImage: "/assets/desert.webp",
    gallery: [
      "/assets/Surf_Experience.jpg",
      "/assets/surf1.png",
      "/assets/surf2.png",
      "/assets/surf3.png",
      "/assets/surf5.png",
      "/assets/surf4.png",
    ],
    order: 8,
    isActive: true,
  },
  {
    id: "program-quad-sunset-taghazout",
    slug: "quad-sunset-adventure-taghazout",
    title: "Quad Sunset Adventure",
    category: "Adventure",
    region: "Taghazout",
    destination: "Taghazout",
    duration: "Half day",
    shortDescription:
      "Ride through beaches and mountain tracks around Taghazout, ending with sunset views and a tea break in nature.",
    places: ["Taghazout"],
    highlights: [
      "Quad biking on beach and mountains",
      "Sunset views",
      "Tea break in nature",
    ],
    coverImage: "/assets/aghadir2.jpg",
    gallery: [
      "/assets/quad1.png",
      "/assets/quad2.png",
      "/assets/quad3.png",
      "/assets/quad4.png",
      "/assets/quad5.png",
      "/assets/quad6.png",
      "/assets/quad7.png",
    ],
    order: 9,
    isActive: true,
  },
  {
    id: "program-essaouira-day-trip",
    slug: "essaouira-day-trip",
    title: "Essaouira Day Trip",
    category: "Coastal",
    region: "Essaouira",
    destination: "Essaouira",
    duration: "Full day",
    shortDescription:
      "A coastal cultural escape to Essaouira's medina, ocean views, port life, and artisan markets.",
    places: ["Essaouira", "Essaouira Medina"],
    highlights: [
      "Historic medina UNESCO atmosphere",
      "Atlantic ocean views",
      "Port and artisan markets",
    ],
    coverImage: "/assets/aghadir3.jpg",
    order: 10,
    isActive: true,
  },
  {
    id: "program-imperial-cities-desert-tours",
    slug: "imperial-cities-desert-tours",
    title: "Imperial Cities & Desert Tours",
    category: "Multi-Day",
    region: "Marrakech / Agafay / Ourika / Ouzoud",
    destination: "Marrakech / Agafay / Ourika / Ouzoud",
    duration: "Multi day",
    shortDescription:
      "A rich Morocco journey combining Marrakech landmarks, souks, gardens, desert experiences, and nearby valleys.",
    places: [
      "Marrakech",
      "Jemaa el-Fnaa",
      "Koutoubia Mosque",
      "Jardin Majorelle",
      "Bahia Palace",
      "Marrakech Souks",
      "Agafay Desert",
      "Ouzoud",
      "Ourika Three Valleys",
    ],
    highlights: [
      "Imperial city atmosphere",
      "Medina and souk discovery",
      "Desert dinner experiences",
      "Gardens, palaces, and cultural landmarks",
      "Mountain valley escapes",
    ],
    coverImage: "/assets/marrakech.jpg",
    gallery: [
      "/assets/Imperial1.png",
      "/assets/Imperial2.png",
      "/assets/Imperial3.png",
      "/assets/Imperial4.png",
    ],
    isMultiDay: true,
    order: 11,
    isActive: true,
  },
  {
    id: "program-atlas-berber-life",
    slug: "atlas-berber-life",
    title: "Atlas & Berber Life",
    category: "Multi-Day",
    region: "Atlas Mountains / Tafraoute / Taroudant",
    destination: "Atlas Mountains / Tafraoute / Taroudant",
    duration: "Multi day",
    shortDescription:
      "A cultural mountain journey focused on Berber life, traditional food, crafts, local markets, and Atlas landscapes.",
    places: ["Atlas Mountains", "Tafraoute", "Taroudant"],
    highlights: [
      "Berber villages and people",
      "Cooking tagine and tea rituals",
      "Mountain landscapes",
      "Local markets and crafts",
    ],
    coverImage: "/assets/ATLAS-PARADISE2.jpg",
    gallery: [
      "/assets/atlas-montain.jpg",
      "/assets/ATLAS-PARADISE1.jpg",
      "/assets/ATLAS-PARADISE2.jpg",
      "/assets/ATLAS-PARADISE3.jpg",
    ],
    isMultiDay: true,
    order: 12,
    isActive: true,
  },
  {
    id: "program-desert-adventure-sahara",
    slug: "desert-adventure-sahara",
    title: "Desert Adventure Sahara",
    category: "Multi-Day",
    region: "Sahara",
    destination: "Sahara",
    duration: "Multi day",
    shortDescription:
      "A cinematic Sahara route through kasbahs, valleys, golden dunes, camel trekking, and desert camp nights.",
    places: ["Ait Ben Haddou", "Ouarzazate", "Merzouga", "Erg Chebbi", "Dades Valley"],
    highlights: [
      "Camel trekking",
      "Golden dunes at sunrise and sunset",
      "Desert camp with fire and music",
      "Starry night desert atmosphere",
    ],
    coverImage: "/assets/jeep_safari4.jpg",
    isMultiDay: true,
    order: 13,
    isActive: true,
  },
  {
    id: "program-north-magic-blue-ocean",
    slug: "north-magic-blue-ocean",
    title: "North Magic Blue & Ocean",
    category: "Multi-Day",
    region: "Tangier / Chefchaouen",
    destination: "Tangier / Chefchaouen",
    duration: "Multi day",
    shortDescription:
      "A northern Morocco journey from ocean cliffs and caves to Chefchaouen's blue streets and rooftop views.",
    places: ["Tangier", "Cap Spartel", "Hercules Caves", "Chefchaouen"],
    highlights: [
      "Blue streets aesthetic",
      "Rooftops and traditional doors",
      "Ocean cliffs",
      "Slow cinematic walking shots",
    ],
    coverImage: "/assets/tanger.jpg",
    gallery: [
      "/assets/North_Magic1.png",
      "/assets/North_Magic2.png",
      "/assets/North_Magic3.png",
      "/assets/North_Magic4.png",
      "/assets/North_Magic5.png",
      "/assets/North_Magic6.png",
      "/assets/North_Magic7.png",
      "/assets/North_Magic8.png",
    ],
    isMultiDay: true,
    order: 14,
    isActive: true,
  },
  {
    id: "program-fes-authentic-soul",
    slug: "fes-authentic-soul",
    title: "Fes Authentic Soul",
    category: "Multi-Day",
    region: "Fes",
    destination: "Fes",
    duration: "Multi day",
    shortDescription:
      "A deep cultural journey into Fes, where ancient alleys, artisans, tanneries, and Islamic architecture define the city's soul.",
    places: ["Fes el Bali", "Chouara Tannery", "Bou Inania Madrasa"],
    highlights: [
      "Tannery colors from top views",
      "Madrasa details and symmetry",
      "Leather, pottery, and weaving artisans",
      "Narrow alleys with morning light rays",
      "Traditional doors and textures",
    ],
    coverImage: "/assets/mosque.jpg",
    gallery: [
      "/assets/fes1.png",
      "/assets/fes2.png",
      "/assets/fes3.png",
      "/assets/fes4.png",
      "/assets/fes5.png",
      "/assets/fes6.png",
      "/assets/fes7.png",
      "/assets/fes8.png",
      "/assets/fes8.png",
      "/assets/fes8.png",
      "/assets/fes9.png",
      "/assets/fes10.png",
      "/assets/fes11.png",
      "/assets/fes12.png",
    ],
    isMultiDay: true,
    order: 15,
    isActive: true,
  },
  {
    id: "program-volubilis-ancient-empire-vibe",
    slug: "volubilis-ancient-empire-vibe",
    title: "Volubilis Ancient Empire Vibe",
    category: "Multi-Day",
    region: "Volubilis",
    destination: "Volubilis",
    duration: "Multi day",
    shortDescription:
      "A heritage stop exploring Morocco's ancient Roman legacy through the ruins and open landscapes of Volubilis.",
    places: ["Volubilis"],
    highlights: [
      "Ancient Roman ruins",
      "Archaeological atmosphere",
      "Heritage storytelling",
      "Wide open historical landscapes",
    ],
    coverImage: "/assets/kasbah.webp",
    isMultiDay: true,
    order: 16,
    isActive: true,
  },
  {
    id: "program-rabat-capital-heritage",
    slug: "rabat-capital-heritage",
    title: "Rabat",
    category: "Multi-Day",
    region: "Rabat",
    destination: "Rabat",
    duration: "Multi day",
    shortDescription:
      "Discover Morocco's capital through historic towers, blue-and-white kasbah streets, gardens, ocean cliffs, and river views.",
    places: ["Hassan Tower", "Kasbah of the Udayas", "Ocean cliffs", "Bouregreg River"],
    highlights: [
      "Hassan Tower wide views",
      "Blue and white streets of the Kasbah",
      "Ocean cliffs and river views",
      "Calm gardens and clean luxury walking routes",
    ],
    coverImage: "/assets/tanger.jpg",
    isMultiDay: true,
    order: 17,
    isActive: true,
  },
  {
    id: "program-casablanca-modern-energy",
    slug: "casablanca-modern-energy",
    title: "Casablanca Modern Energy",
    category: "Multi-Day",
    region: "Casablanca",
    destination: "Casablanca",
    duration: "Multi day",
    shortDescription:
      "A modern coastal city experience built around Casablanca's mosque, corniche, cafes, sunset views, and urban energy.",
    places: ["Hassan II Mosque", "Corniche", "Modern city districts"],
    highlights: [
      "Hassan II Mosque with ocean views",
      "Corniche lifestyle, cafes, and coastline",
      "Modern city energy",
      "Sunset by the ocean",
      "Urban night lights",
    ],
    coverImage: "/assets/moroccoblue.jpg",
    isMultiDay: true,
    order: 18,
    isActive: true,
  },
];

export const PROGRAMS_SEED = MOROCCO_PROGRAMS;
